* se agrega la funcion instalar

diff --git a/xsign b/xsign
--- a/xsign
+++ b/xsign
@@ -3,6 +3,17 @@
 # Licence: GPL-2
 LC_ALL=C
 
+if ! [[ -f /usr/bin/gpg ]] || [[ $(dpkg --get-selections | grep -w "gnupg" | awk '{print $1}' | head -1) != gnupg ]]; then
+	if [[ "$EUID" != "0" ]]; then
+		echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
+		exit 1
+	fi
+	apt-get -q update
+	apt-get -qy install gnupg gpgv
+	echo "Instalacion finalizada..."
+	exit 0
+fi
+
 if [[ "$EUID" = "0" ]]; then
 	echo "ERROR: No debe ser root."
 	exit 1
